name = "biblioteca"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Variables de entorno
[vars]
R2_PUBLIC_URL = "https://biblioteca-files.your-account.r2.cloudflarestorage.com"
ENVIRONMENT = "development"
NODE_VERSION = "18.17.0"

# Configuración para desarrollo
[env.development]
name = "biblioteca-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "biblioteca-db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"

[[env.development.r2_buckets]]
binding = "BUCKET"
bucket_name = "biblioteca-files-dev"

# Configuración para producción
[env.production]
name = "biblioteca-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "biblioteca-db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "biblioteca-files"

# Configuración para Pages
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "18.17.0"
NPM_VERSION = "9.8.1"

# Configuración de compatibilidad
[compatibility_flags]
nodejs_compat = true
